name: End-to-end Example tests
on: push
  paths:
    - 'cypress/e2e/1-getting-started/todo.cy.js'
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/1-getting-started/todo.cy.js