name: Saucedemo Login
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run Saucedemo
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/3-web/saucedemo/login.cy.js
      - uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore